#spring.application.name=jp-capacitacao-2026
#spring.jpa.hibernate.ddl-auto=update
spring:
  application:
    name: jp-capacitacao-2026

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: ${URL_DB:jdbc:oracle:thin:@//localhost:1521/FREE}
    username: ${USERNAME_DB:system}
    password: ${PASSWORD_DB:Arroz@123}
    driverClassName: oracle.jdbc.driver.OracleDriver

server:
  port: 9090